Algoritmo "exemploPARA"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/11/2023
Var
   cont : inteiro

   para cont de 1000 ate cont >= 1500 passo 1 faca
      se cont % 2 = 1 entao
         escreva(cont)
      fimse


Inicio


Fimalgoritmo